name: Build (WinUI 3)
on: [push, pull_request]
jobs:
  build-architectures:
    runs-on: windows-latest
    
    strategy:
      matrix:
        architecture: [x64, x86, arm64]
        configuration: [Debug, Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Restore
        run: msbuild /t:Restore
      - name: Build
        run: msbuild /t:Build /p:Platform=${{ matrix.architecture }} /p:Configuration=${{ matrix.configuration }} /p:GenerateAppxPackageOnBuild=true /p:PublishAot=${{ matrix.configuration == 'Debug' && 'false' || 'true' }}
      - name: Copy build binaries
        run: |
          Get-ChildItem -Path . -Recurse -Filter *.msix |
          Where-Object { $_.FullName -notmatch '\\Dependencies\\' } |
          ForEach-Object {
            Copy-Item -Path $_.FullName -Destination . -Force
          }
      - name: Copy build symbols
        run: |
          $folderSearch = "${{ matrix.configuration == 'Release' && '\\native\\' || '' }}"
          Get-ChildItem -Path . -Recurse -Filter *.pdb |
          Where-Object { $_.FullName -match $folderSearch } |
          ForEach-Object {
            Copy-Item -Path $_.FullName -Destination . -Force
          }
      - name: Upload build binaries
        uses: actions/upload-artifact@v4
        with:
          name: Binaries - ${{ matrix.configuration }} - ${{ matrix.architecture }}
          path: "*.msix"
      - name: Upload build symbols
        uses: actions/upload-artifact@v4
        with:
          name: Symbols - ${{ matrix.configuration }} - ${{ matrix.architecture }}
          path: "*.pdb"
