name: Build (WinUI 3)
on:
  push:
    branches: [ "reset-winui3" ]
    tags:
      - '*'
  pull_request:
    branches: [ "reset-winui3" ]
    
jobs:
  build:
    runs-on: windows-latest

    permissions:
      id-token: write
    
    strategy:
      matrix:
        channel: [AppInstaller, Store]
        include:
          - channel: AppInstaller
            publisher:
              "CN=Đặng Bình Minh, O=Đặng Bình Minh, L=Hà Nội, C=VN"
            pkgName:
              "MicaForEveryone.MicaForEveryone2"
          - channel: Store
            publisher:
              "CN=95B8F56A-76FA-4743-83B0-5312C49D625D"
            pkgName:
              "DongleInsovaki.MicaForEveryone"

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
      - name: Change package identity
        run: |
          $manifestPath = "MicaForEveryone.App\Package.appxmanifest"

          $manifest = [xml](Get-Content $manifestPath)
          $manifest.Package.Identity.Publisher = "${{ matrix.publisher }}"
          $manifest.Package.Identity.Name = "${{ matrix.pkgName }}"

          $manifest.Save($manifestPath)
      - name: Login to Azure
        uses: azure/login@v3
        if: github.ref_type == 'tag'
        with:
          client-id: ${{ secrets.TS_CLIENT_ID }}
          tenant-id: ${{ secrets.TS_TENANT_ID }}
          subscription-id: ${{ secrets.TS_SUBSCRIPTION_ID }}
      - name: Create Trusted Signing configuration
        if: github.ref_type == 'tag'
        run: |
          $config = @{
            Endpoint = "${{ secrets.TS_ENDPOINT }}"
            CodeSigningAccountName = "${{ secrets.TS_ACCOUNT }}"
            CertificateProfileName = "${{ secrets.TS_CERT }}"
          }
          $json = $config | ConvertTo-Json
          $json | Out-File -FilePath "${{ github.workspace }}\trusted-signing.json"
      - name: Set App Center connection string
        if: github.ref_type == 'tag'
        run: |
          $xmlPath = "${{ github.workspace}}\MicaForEveryone.App\appsettings.resw"
          [xml]$xml = Get-Content -Path $xmlPath
          $xml.root.data | Where-Object { $_.name -eq "AppCenterConnectionString" } | ForEach-Object {
            $_.value = "${{ secrets.AC_STRING }}"
          }
          $xml.Save($xmlPath)
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build MicaForEveryone.App\MicaForEveryone.App.csproj /p:Platform=x64 -c Release /p:GenerateAppxPackageOnBuild=true /p:UapAppxPackageBuildMode=${{ matrix.channel == 'Store' && 'CI' || 'SideloadOnly' }} /p:TrustedSigningEnabled=${{ github.ref_type == 'tag' && 'true' || 'false'}} /p:TrustedSigningMetadataPath="${{ github.workspace }}\trusted-signing.json" --no-restore
      - name: Copy build binaries
        run: |
          Get-ChildItem -Path . -Recurse -Include ("*.msixupload", "*.msixbundle", "*.appxsym") |
          Where-Object { $_.FullName -notmatch '\\Dependencies\\' } |
          ForEach-Object {
            Copy-Item -Path $_.FullName -Destination . -Force
          }
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.channel == 'Store' && 'StorePackage' || 'AppInstallerPackage' }}
          path: |
            ${{ matrix.channel == 'Store' && '*.msixupload' || '*.msixbundle' }}
            ${{ matrix.channel == 'Store' && '' || '*.appxsym' }}