name: Publish
on:
  push:
    tags: [ "*" ]

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      release: true
    secrets: inherit
  add-release-artifacts:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          name: AppInstallerPackage
      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            ./*.msixbundle
            ./Dependencies/*.msix
            ./*.appinstaller
          draft: true